# Site settings
title: "Dev Misra"
description: "<h3>Welcome to my portfolio!</h3> <p>Technology, strategy, and analytics at the intersection of AI and business.</p>"
url: "https://31-DM.github.io"
email_address: dam387@cornell.edu
linkedin_username: 'dev-misra'
github_username: '31-DM'

# Enable navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/projects/', text: 'Projects' }
  - { url: '/about/', text: 'About' }
  - { url: '/resume.pdf', text: 'Resume' }
  - { url: '/contact/', text: 'Contact' }

# Footer
footer_text: '© 2025 Dev Misra'
admin_name: 'Dev Misra'

# Jekyll settings (REQUIRED FOR POSTS TO SHOW)
permalink: /:categories/:title/
paginate: 10
paginate_path: "/page:num/"
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Plugins (Pagination Support)
plugins:
  - jekyll-paginate
